---
title: "Tema 4. Distribución de comunidades"
output: revealjs::revealjs_presentation
bibliography: biblio.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introducción

* **Distribución y abundancia** de una especie siempre resultan afectados por otras especies.

* Debido a las interacciones entre organismos, normalmente las distribuciones de especies suelen ser **mutuamente excluyentes a escala local**, o tienden a ocurrir de forma conjunta en complejas comunidades ecológicas.

* Las comunidades vistas como un superorganismo se atribuye a **Clements** (especies como células).

* En contraste, la comunidad vista como unida discreta e integrada, se atribuye a **Gleason**.

## Introducción (cont.)

* Ambas corrientes hicieron aportes relevantes.
    * Las comunidades exhiben **atributos como los de un individuo** ("productividad primaria total").
    
    * Por otra parte, las especies también varían en "ocurrencia" y abundancia **como si fuesen organismos indpendientes** unos de otros.

* Climas diferentes inducen tipos de __vegetación distintos__ (zonas de vida, biomas, ecorregiones).

* Ejemplo: ...

* Consultar mapas modelos idealizados, pags. 15 y 39 de @bailey2014ecoregions.


## Comunidades y ecosistemas

* Je je, __tremendo lío__, definiciones arbitrarias.

* Las comunidades y los ecosistemas son los niveles de organización biótica y ecológica __más altos__, pero comúnmente se deifnen de forma arbitraria.

## Comunidades y ecosistemas (cont.)

### Comunidad

* La comunidad consiste en el __conjunto de especies que viven en el mismo lugar__.

* Un miembro de la comunidad puede definirse __taxonómicamente__ o por medio de atributos/rasgos __funcionales__ (e.g. formas de vida, dieta).

* Dos atributos son recurrentemente estudiados en la comunidad: __estructura__ (atributos estáticos) y __funciones__ (atributos dinámicos).

* Los límites se establecen __arbitrariamente__, aunque los __rasgos topográficos__ son usados también.

## Comunidades y ecosistemas (cont.)

### Ecosistemas

* Incluye no sólo las especies que habitan en el lugar, sino también los __rasgos/atributos/características físicas__ del mismo, así como las interacciones entre los componentes bióticos y abióticos del sistema.

* __Los ecosistemas no están aislados__, aunque lo parezcan. El ecosistema más grande y aislado del resto es la biosfera, pero dentro de ella, es difícil separar subunidades que se consideren absolutamente aisladas.

## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas

* Cada especie tiene un nicho, y el cómo se organizan para dar lugar a asociaciones complejas entre poblaciones es el objetivo último de la ecología.

* Dos rasgos son fundamentales de las especies que influyen en la comunidad son su __masa/volumen corporal__ y su __estado trófico o condición trófica__.

## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Masa corporal

* Su influencia sobre el ecosistema es significativamente alta.

* A __mayor tamaño/masa, mayor consumo__ energético. La tasa de metabolismo basal es clave ($m=cM^{0.75}$).

* Hay más especies de animales pequeños, y son igualmente más abundantes, que grandes.

* Las __especies grandes__ (al menos en animales), tienden a tener __ámbitos geográficos amplios__.

## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Masa corporal

* La __capacidad de carga__ del ambiente es limitada, por lo que los animales grandes tienden a aumente su rango para compensar esta limitación.

* Ver figuras 5.2 y 5.3, páginas 125 y 126 de @lomolino2006biogeography.

## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Estado trófico

* Se refiere a __cómo los organismos adquieren su energía__, y es el otro rasgo que influye significativamente en la comunidad.

* El tamaño corporal tiene efecto sobre el estado trófico. Los __depredadores suelen ser más grandes que su presa__, a menos que la especie realice caza en manadas.

## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Estado trófico

* Los organismos obtienen __su energía del sol__ (salvo contadas excepciones).

* Las plantas, autótrofos, producen __compuestos orgánicos a partir de radiación solar__, dióxido de carbono, minerales y agua.

* Además de usarlo en su metabolismo, las plantas producen estos compuestos para otros organismos que se alimentan de ellos, y otros organismos se alimentan de estos últimos.


## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Estado trófico

* El diseño de trayectorias unidireccionales de la energía que fluye entre especies y a través de comunidades se denominan __cadenas tróficas__. Los nodos de la misma se denominan __niveles tróficos__.

* El primer nivel contiene plantas, o __productores primarios__. El segundo contiene herbívoros, o __consumidores primarios__. El tercero __carnívoros__ o consumidores, y así sucesivamente. Al final de las cadenas están los __descomponedores o detritívoros__.


## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Estado trófico

* Aunque la __energía fluye linealmente__, los trayectos que sigue la energía son muy variados. Un consumidor se alimenta comúnmnente de __varias especies__, y varios __descomponedores lo consumirán__, formando una red trófica (distintas cadenas interconectadas; ver figura 5.5, página 127 de @lomolino2006biogeography).
* La energía fluye a través de las comunidades siguiendo la __primera__ (la energía ni se crea ni se destruye) y la __segunda ley de la termodinámica__ (a mayor conversión de la energía, menor su capacidad de producir trabajo, su caos/entropía aumenta).


## Comunidades y ecosistemas (cont.)

### Consideraciones energéticas (cont.)

#### Estado trófico

* Pirámides de flujo energético. Estados tróficos más altos disponen de menor cantidad de energía.

* Capacidad de carga: energía utilizable. La capacidad de carga de un área para estados tróficos altos es baja.

## Referencias
